### ISSUE TITLE
Combinations of input

### ISSUE THREAD

**Issue by ath88** [hypesystem/jasmine-theories#3]
I have this case;

```
describe("constructor", function() {
    it("fails when at least one object doesn't pass validation", function() {
        var constructor;

        constructor = function() { new Item("something wrong", "something wrong"); };
        expect(constructor).toThrow();

        constructor = function() { new Item(goodFirstArgument, "something wrong"); };
        expect(constructor).toThrow();

        constructor = function() { new Item("something wrong", goodSecondArgument); };
        expect(constructor).toThrow();
    });
});
```

How could this be handled through jasmine-theories? Maybe adding some functionality that creates permutations of input might be prudent?

**Comment by hypesystem** [comment]
How about:

``` js
describe("constructor", function() {
    it("fails when at least one object doesn't pass validation", [
      [ "something wrong", "something wrong" ],
      [ goodFirstArgument, "something wrong" ],
      [ "something wrong", goodSecondArgument ]
    ], function(args) {
        var constructor = function() { new Item(args[0], args[1]); };
        expect(constructor).toThrow();
    });
});
```

**Comment by hypesystem** [comment]
Alternatively, you can pass objects `{}` to the array of values to get named indexes.

**Comment by ath88** [comment]
This still requires me to supply all relevant permutations. In cases where I would like to test with several different values the list quickly increases in size. Imagine the `NumberStack` taking two input with just 4 different values;

```
describe("constructor", function() {
    it("fails when at least one object doesn't pass validation", [
      [ null, null ],
      [ false, false ],
      [ new Error("hello"), new Error("hello") ],
      [ "str", "str" ],
      [ null, false ],
      [ null, new Error("hello) ],
      [ null, "str" ],
      [ false, null ],
      [ new Error("hello), null ],
      [ "str", null ],
      ...
    ], function(args) {
        var constructor = function() { new NumberStack(args[0], args[1]); };
        expect(constructor).toThrow();
    });
});
```

**Comment by hypesystem** [comment]
Very true, but in your new example there is no test of "first argument valid, second argument invalid". It only tests what happens if both inputs are invalid :smile:

**Comment by hypesystem** [comment]
I think this is a somewhat sought out case; it will very rarely be the case that so many combinations are needed.

**Comment by ath88** [comment]
Adding a valid argument in there would only make the array even larger. It should be possible to build a construct that fully searches the entire combinatoric space.

It will be rare? In black-box testing, this is indeed useful. Having the ability to supply 20 different arguments would be powerful.

**Comment by hypesystem** [comment]
Unit tests are white box tests.

**Comment by hypesystem** [comment]
What you are suggesting is not the intended use for jasmine-theories -- at least not at the moment. The intention is to support common unit test cases.

**Comment by ath88** [comment]
Ill go elsewhere with my black-box testing then. :) Thanks for the response!
